[package]
name = "dm-plugin-ssh"
version = "0.2.0"
edition = "2024"
rust-version = "1.99.0"
description = "Manage saved SSH server connections"
license = "MIT"
publish = false
repository = "https://github.com/guangl/dm-plugin-ssh"
readme = "README.md"

[lib]
name = "dm_plugin_ssh"
path = "src/lib.rs"

[[bin]]
name = "dm-ssh"
path = "src/main.rs"

[dependencies]
dm-plugin-support = { version = "0.1.0", git = "https://github.com/guangl/dm-plugin-support.git", rev = "9304a71f65bd4819a50a47aed40016e339e0ead7" }
aes-gcm = "0.11"
anyhow = "1.0"
clap = { version = "4.6", features = ["derive"] }
comfy-table = "8.0"
dm-plugin-sdk = { version = "0.4.1", git = "https://github.com/guangl/dm-plugin-sdk.git", rev = "b12ce0d937e2f732151b30a1850e08ed4e5c9cf9" }
pbkdf2 = "0.13"
rand = "0.10"
rpassword = "7.5.4"
rusqlite = { version = "0.40", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.11"
toml = "1.1.6"
russh = { version = "0.63.3", default-features = false, features = ["ring", "rsa"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "time", "io-std", "io-util", "macros"] }
crossterm = "0.29.0"
fs2 = "0.4.3"

[dev-dependencies]
tempfile = "3.27"
